///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WebTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WebTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("445a972b-89a7-4bbc-ba73-52bab36f115a")]
    public partial class WebTestRepository : RepoGenBaseFolder
    {
        static WebTestRepository instance = new WebTestRepository();
        WebTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        WebTestRepositoryFolders.OnlineShoppingSiteInIndiaShopOnliAppFolder _onlineshoppingsiteinindiashoponli;

        /// <summary>
        /// Gets the singleton class instance representing the WebTestRepository element repository.
        /// </summary>
        [RepositoryFolder("445a972b-89a7-4bbc-ba73-52bab36f115a")]
        public static WebTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WebTestRepository() 
            : base("WebTestRepository", "/", null, 0, false, "445a972b-89a7-4bbc-ba73-52bab36f115a", ".\\RepositoryImages\\WebTestRepository445a972b.rximgres")
        {
            _applicationundertest = new WebTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _onlineshoppingsiteinindiashoponli = new WebTestRepositoryFolders.OnlineShoppingSiteInIndiaShopOnliAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("445a972b-89a7-4bbc-ba73-52bab36f115a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("93976a88-5b76-41a8-aaf7-d62960a58140")]
        public virtual WebTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The OnlineShoppingSiteInIndiaShopOnli folder.
        /// </summary>
        [RepositoryFolder("e283a8d7-129c-424b-ab91-7fc27675d33b")]
        public virtual WebTestRepositoryFolders.OnlineShoppingSiteInIndiaShopOnliAppFolder OnlineShoppingSiteInIndiaShopOnli
        {
            get { return _onlineshoppingsiteinindiashoponli; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class WebTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("93976a88-5b76-41a8-aaf7-d62960a58140")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchdropdownboxInfo;
            RepoItemInfo _navsearchsubmitbuttonInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.amazon.com']", parentFolder, 30000, null, false, "93976a88-5b76-41a8-aaf7-d62960a58140", "")
            {
                _searchdropdownboxInfo = new RepoItemInfo(this, "SearchDropdownBox", ".//select[#'searchDropdownBox']", ".//select[#'searchDropdownBox']", 30000, null, "e8aa1095-775e-421a-a924-edbc53e040cb");
                _navsearchsubmitbuttonInfo = new RepoItemInfo(this, "NavSearchSubmitButton", ".//input[#'nav-search-submit-button']", ".//input[#'nav-search-submit-button']", 30000, null, "118f677f-9587-445b-81db-a07881a6770f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("93976a88-5b76-41a8-aaf7-d62960a58140")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("93976a88-5b76-41a8-aaf7-d62960a58140")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchDropdownBox item.
            /// </summary>
            [RepositoryItem("e8aa1095-775e-421a-a924-edbc53e040cb")]
            public virtual Ranorex.SelectTag SearchDropdownBox
            {
                get
                {
                    return _searchdropdownboxInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SearchDropdownBox item info.
            /// </summary>
            [RepositoryItemInfo("e8aa1095-775e-421a-a924-edbc53e040cb")]
            public virtual RepoItemInfo SearchDropdownBoxInfo
            {
                get
                {
                    return _searchdropdownboxInfo;
                }
            }

            /// <summary>
            /// The NavSearchSubmitButton item.
            /// </summary>
            [RepositoryItem("118f677f-9587-445b-81db-a07881a6770f")]
            public virtual Ranorex.InputTag NavSearchSubmitButton
            {
                get
                {
                    return _navsearchsubmitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NavSearchSubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("118f677f-9587-445b-81db-a07881a6770f")]
            public virtual RepoItemInfo NavSearchSubmitButtonInfo
            {
                get
                {
                    return _navsearchsubmitbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The OnlineShoppingSiteInIndiaShopOnliAppFolder folder.
        /// </summary>
        [RepositoryFolder("e283a8d7-129c-424b-ab91-7fc27675d33b")]
        public partial class OnlineShoppingSiteInIndiaShopOnliAppFolder : RepoGenBaseFolder
        {
            NavLogoSpritesInfoClass _navlogospritesInfo;

            /// <summary>
            /// Creates a new OnlineShoppingSiteInIndiaShopOnli  folder.
            /// </summary>
            public OnlineShoppingSiteInIndiaShopOnliAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OnlineShoppingSiteInIndiaShopOnli", "/dom[@domain='www.amazon.in']", parentFolder, 30000, null, false, "e283a8d7-129c-424b-ab91-7fc27675d33b", "")
            {
                _navlogospritesInfo = new NavLogoSpritesInfoClass(this);
            }

            /// <summary>
            /// The NavLogoSpritesInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("14a296a3-d090-4e7e-a7a1-8eb7ec5c6b58")]
            public class NavLogoSpritesInfoClass : RepoItemInfo
            {
                /// <summary>
                /// NavLogoSpritesInfoClass class constructor.
                /// </summary>
                public NavLogoSpritesInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "NavLogoSprites", ".//a[#'nav-logo-sprites']", 30000, null, "14a296a3-d090-4e7e-a7a1-8eb7ec5c6b58")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("b190e0d1-d987-4f50-b667-8ed89196f4b0")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("b190e0d1-d987-4f50-b667-8ed89196f4b0");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("b190e0d1-d987-4f50-b667-8ed89196f4b0")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("b190e0d1-d987-4f50-b667-8ed89196f4b0", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e283a8d7-129c-424b-ab91-7fc27675d33b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e283a8d7-129c-424b-ab91-7fc27675d33b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NavLogoSprites item.
            /// </summary>
            [RepositoryItem("14a296a3-d090-4e7e-a7a1-8eb7ec5c6b58")]
            public virtual Ranorex.ATag NavLogoSprites
            {
                get
                {
                    return _navlogospritesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NavLogoSprites item info.
            /// </summary>
            [RepositoryItemInfo("14a296a3-d090-4e7e-a7a1-8eb7ec5c6b58")]
            public virtual NavLogoSpritesInfoClass NavLogoSpritesInfo
            {
                get
                {
                    return _navlogospritesInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
